YML changes

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Deploy Next.js App to EC2
+name: Deploy next 
 
 on:
   push:
@@ -8,22 +8,25 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Deploy to Server (as ubuntu)
+        uses: appleboy/ssh-action@v0.1.9
+        with:
+          host: 3.109.49.243
+          username: ubuntu
+          key: ${{ secrets.EC2_SSH_KEY}}
+          port: 22
+          script: |
+            set -euo pipefail
+            echo "Starting deploy as LexHouse on $(hostname) ..."
 
-    - name: Setup SSH
-      uses: webfactory/ssh-agent@v0.8.0
-      with:
-        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
+            # App path
+            cd /var/www/html/GitHub-actions-CICD-EC2/ || { echo "path not found"; exit 1; }
 
-    - name: Deploy to EC2
-      run: |
-        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-          cd /var/www/html/GitHub-actions-CICD-EC2
-          git pull origin main
-          npm install
-          npm run build
-          pm2 reload 0
-        EOF
+
+            git pull origin main
+            npm install
+            npm run build
+
+            pm2 reload 0
+            echo "Deploy finished."
